www/views.py
#!/usr/bin/env python

"""The Astronomical Algorithms Implemented in C++ and Python Web UI using Flask

To run: ./bin/pylaunch.sh aai.py

with rotating logging: ./pylaunch.sh aai.py -l debug --loghandler rotating --logfilename ./logs/aai-flask.log
"""

import argparse
import flask
import logging
import logging.handlers



home_page = flask.Blueprint('home_blueprint', __name__, template_folder='templates')



@home_page.route("/")
def home():
    """Application's home"""

    return flask.render_template('home.html')


@home_page.route("/lunar_daily_altitude_chart")
def lunar_daily_altitude_chart():
    """Plot the moon's altitude for the observer's location"""

    return flask.render_template('lunar_daily_altitude_chart.html')


@home_page.route("/solar_azimuth_map")
def solar_azimuth_map():
    """Plot the sun's azimuth for the observer's location"""

    return flask.render_template('solar_azimuth_map.html')


@home_page.route("/solar_daily_altitude_chart")
def solar_daily_altitude_chart():
    """Plot the sun's altitude for the observer's location"""

    return flask.render_template('solar_daily_altitude_chart.html')


@home_page.route("/transform_observations")
def transform_observations():
    """Transform observation coordinates at observer's location"""

    return flask.render_template('transform_observations.html')


@home_page.route("/transform_times")
def transform_times():
    """Transform various time formats like deg:min:sec to decimal degrees"""

    return flask.render_template('transform_times.html')


@home_page.route("/accuracy")
def accuracy():
    """Accuracy page"""

    return flask.render_template('accuracy.html')

www/templates/accuracy.html
{% extends "base.html" %}

{% block title %}Astronomical Algorithms Implemented{% endblock %}

{% block content %}


<h1>Astronomical Algorithms Implemented</h1>

<h2>On Accuracy</h2>

<br>

<div id="accuracy" class="twocolumn">

  I have been working on several ways to test the accuracy of the model.
  Beyond noting the sun rise and set times along with local noon on an
  improvised sun dial (the sunbeam from the skylight on my south facing
  stairs), I have used a
  <a href="https://www.starpath.com/catalog/accessories/1840d15.htm">Davis
    Mark-15 Plastic Sextant</a>
  with a swimming pool as an artificial horizon.
  While I have no training other than what came in the instructions with
  the sextant, on a clam day with a stable reflection I get results
  within a couple arc minutes of my calculations.
  I use these results in the
  <a href="https://github.com/lrmcfarland/Astronomy/blob/master/Bodies/test_SunPosition.py">source
    code unit tests</a>.

  <p>
    I also have agreement within a couple minutes of other sites like the
    <a href="http://www.esrl.noaa.gov/gmd/grad/solcalc/">NOAA solar calculator</a>
    and the
    <a href="http://aa.usno.navy.mil/index.php">Astronomical Applications
      Department of the U.S. Naval Observatory</a>

    And in references like Wikipedia's
    <a href="https://en.wikipedia.org/wiki/Midnight_sun">midnight sun
      reference</a>, I get the results they have for the rise, transit and
    set times for Fairbanks, Alaska, when making the adjustments for time
    zone they list.

  <p>
    The picture below was taken (on 2016-05-08) with the iOS
    <a href="https://itunes.apple.com/us/app/theodolite/id339393884?mt=8">
      Theodolite</a> app (I have no connection to them other than as a
    satisfied customer.)  When I enter the time and location coordinates,
    I get good agreement in altitude (my 22.87&deg; vs. their 22.3&deg;)
    and am only off by about 10&deg; azimuth (274.73&deg; vs. 265&deg;),
    and some of that I would attribute to some "stickiness" in the
    sensors.


  <p>

    From Meeus' Example 13.b, the observer's location is at the
    U.S. Naval Observatory at Washington, D.C.: Latitude 38:55:17,
    Longitude -77:03:56 (in my ":" notation for degrees, minutes,
    seconds and using the IAU positive east convention for latitude
    instead of Meeus'); Venus' right ascension is 23:09:16.641 hours and
    declination -6:43:11.61 degrees.  On 1987-04-10 at 19:21:00 UT,
    Venus was 15.215 degrees above the horizon, bearing 248.0335 from
    the north, which matches Meeus' results after adjusting his bearing
    of 68.0337 degrees from the south.


</div>

<br>

<img src="static/images/sun_position_1.jpg" height="500" width="100%">



{% endblock %}

www/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.js"></script>
  <script type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <script type="text/javascript" src="{{ url_for('static', filename='aai.js') }}"></script>


  {% block scripts %}{% endblock %}

  <title>{% block title %}{% endblock %}</title>


  {% endblock %}
</head>

<body>
  <div class=page>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
    <div id="footer">
      {% block footer %}
      <hr>
      <a href="{{ url_for('home_blueprint.home') }}">AAI home</a>
      <a href="https://www.starbug.com">starbug.com</a>
      {% endblock %}
    </div>
  </div>
</body>

</html>

www/templates/daily_solar_altitude_chart.html
{# AAI daily solar altitude chart #}

{% extends "base.html" %}

{% block scripts %}

  <script type="text/javascript">

    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};

    {# -------------------- #}
    {# ----- init map ----- #}
    {# -------------------- #}


    {# ----- draw chart ----- #}


    google.charts.load('current', {'packages':['corechart']});

    function updateSunChart(sun_position_data) {

	if (sun_position_data.errors.length > 0) {

	    $("#rising").text("TBD");
	    $("#transit").text("TBD");
	    $("#setting").text("TBD");
	    $("#azimuth").text("TBD");
	    $("#altitude").text("TBD");

	    alert("Errors: " + sun_position_data.errors.join(", "));

	} else {

	    $("#rising").text(sun_position_data.rising);
	    $("#transit").text(sun_position_data.transit);
	    $("#setting").text(sun_position_data.setting);
	    $("#azimuth").text(sun_position_data.sun_marker_azimuth);
	    $("#altitude").text(sun_position_data.sun_marker_altitude);


	    $('input[name="latitude"]').val(sun_position_data.latitude);
	    $('input[name="longitude"]').val(sun_position_data.longitude);


	    {# TODO meh! use regex #}
	    var a_datetime = sun_position_data.datetime.split('T');
	    var a_timeandzone = [a_datetime[1], 0];
	    var a_sign = '';

	    if (/-/.test(a_datetime[1])) {

		a_timeandzone = a_datetime[1].split('-');
		a_sign = '-';

	    } else if (/\+/.test(a_datetime[1])) {

		a_timeandzone = a_datetime[1].split('+');
		a_sign = '+';

	    } else {
		{# pass #}
	    }

	    $('input[name="date"]').val(a_datetime[0]);

	    $('input[name="time"]').val(a_timeandzone[0]);
	    $('input[name="timezone"]').val(a_sign + a_timeandzone[1]);


	    drawSunChart(sun_position_data);
	};

    }; {# end updateSunChart(sun_position_data) #}


    function drawSunChart(sun_position_data) {

	{# ----- formatting for google chart ----- #}
	var sun_plot_data = [['time',
			      'Vernal Equinox',
			      'Summer Solstice',
			      'Autumnal Equinox',
			      'Winter Solstice',
			      sun_position_data.sun_date_label,
			      {'type': 'string', 'role': 'style'}]];

	{# ----- special format for sun marker ----- #}

	for (var i = 0; i < sun_position_data.altitude_data_24h.length - 1; i++) {

	    var plot_record = sun_position_data.altitude_data_24h[i];
	    var next_plot_record = sun_position_data.altitude_data_24h[i+1];

	    if (sun_position_data.sun_marker_time == plot_record[0]) {

		plot_record.push('point { size: 18; shape-type: circle; fill-color: #FFD700; }');

	    } else if (sun_position_data.sun_marker_time > plot_record[0] &&
		       sun_position_data.sun_marker_time < next_plot_record[0]) {

		plot_record.push('point { size: 18; shape-type: circle; fill-color: #FFD700; }');

	    } else if (i == sun_position_data.altitude_data_24h.length - 1 &&
		       sun_position_data.sun_marker_time == next_plot_record[0]) {

		plot_record.push('point { size: 18; shape-type: circle; fill-color: #FFD700; }');

	    } else if (sun_position_data.sun_marker_time > next_plot_record[0]) {

		plot_record.push(null);

	    } else {

		plot_record.push(null);

	    }


	    sun_plot_data.push(plot_record);

	}

	var altitudeVtime_chart = new google.visualization.LineChart(
	    document.getElementById('altitudeVtime'));

	var altitude_table = google.visualization.arrayToDataTable(sun_plot_data);
	var altitude_view = getSunChartView(altitude_table, "Altitude over time for one day", "hour");

	altitudeVtime_chart.draw(altitude_view.data, altitude_view.options);

	{# ----- make toggles active ----- #}

	$("#_vernal_equinox_cb").change(function() {
	  var altitude_view = getSunChartView(altitude_table);
	  altitudeVtime_chart.draw(altitude_view.data, altitude_view.options);
	});

	$("#_summer_solstice_cb").change(function() {
	  var altitude_view = getSunChartView(altitude_table);
	  altitudeVtime_chart.draw(altitude_view.data, altitude_view.options);
	});

	$("#_autumnal_equinox_cb").change(function() {
	  var altitude_view = getSunChartView(altitude_table);
	  altitudeVtime_chart.draw(altitude_view.data, altitude_view.options);
	});

	$("#_winter_solstice_cb").change(function() {
	  var altitude_view = getSunChartView(altitude_table);
	  altitudeVtime_chart.draw(altitude_view.data, altitude_view.options);
	});


    }; {# end drawSunChart(sun_position_data) #}


    function getSunChartView (data_table, chart_title, hAxis_title) {

	var view_data = {};

	var current_color = "blue";
	var vernal_color = "green";
	var summer_color = "red";
	var autumnal_color = "orange";
	var winter_color = "cyan";


	var options = {

	    legend: "none",

	    chartArea: {left: "10%", top: "10%", width:"90%", height:"80%"},

	    title: chart_title,

	    hAxis: { title: hAxis_title},
	    vAxis: { title: "altitude in degrees above the horizon", minValue: -100, maxValue: 100},

	    series: {
		0: { lineDashStyle: [] }
	    },

	    colors: [current_color],

	    pointSize: 1,
	    dataOpacity: 0.7

	};


	var data = new google.visualization.DataView(data_table);

	var hides = [];
	var line_count = 0; {# assumes order ve, ss, ae, ws, current time #}

	if ($("#_vernal_equinox_cb").is(':checked')) {
	    options.series[line_count++] = { color: vernal_color, lineDashStyle: [4, 2] };
	} else {
	    hides.push(1);
	};


	if ($("#_summer_solstice_cb").is(':checked')) {
	    options.series[line_count++] = { color: summer_color, lineDashStyle: [8, 4] };
	} else {
	    hides.push(2);
	};


	if ($("#_autumnal_equinox_cb").is(':checked')) {
	    options.series[line_count++] = { color: autumnal_color, lineDashStyle: [16, 4] };
	} else {
	    hides.push(3);
	};


	if ($("#_winter_solstice_cb").is(':checked')) {
	    options.series[line_count++] = { color: winter_color, lineDashStyle: [32, 4] };
	} else {
	    hides.push(4);
	};

	data.hideColumns(hides);

	view_data['data'] = data;
	view_data['options'] = options;

	return view_data;

    };


    {# ----------------- #}
    {# ----- ready ----- #}
    {# ----------------- #}

    $(document).ready(function() {

	{# ----- get data ----- #}

	$("#get_daily_solar_altitude").click(function(e) {

	    $.getJSON($SCRIPT_ROOT + "/api/v1/daily_solar_altitude",
		      {
			  latitude: $('input[name="latitude"]').val(),
			  longitude: $('input[name="longitude"]').val(),
			  date: $('input[name="date"]').val(),
			  time: $('input[name="time"]').val(),
			  timezone: $('input[name="timezone"]').val(),
			  dst: $("#_dst").is(':checked') {# jQuery selector #}

		      },
		      function(sun_position) {

			  updateSunChart(sun_position);

		      }); {# end getJSON #}

	    return false;

	}); {# end get_daily_solar_altitude click #}



	$("#get_midnight_sun").click(function(e) {

	    $.getJSON($SCRIPT_ROOT + "/api/v1/daily_solar_altitude",
		      {
			  latitude: '66:33',
			  longitude: '0:0:0',
			  date: '2018-06-21',
			  time: '12:00:00',
			  timezone: '0',
			  dst: 'false'
		      },
		      function(sun_position) {

			  updateSunChart(sun_position);

		      }); {# end getJSON #}

	    return false;

	}); {# end get_midnight_sun click #}


	$("#get_darkness_at_noon").click(function(e) {

	    $.getJSON($SCRIPT_ROOT + "/api/v1/daily_solar_altitude",
		      {
			  latitude: '66:33',
			  longitude: '0:0:0',
			  date: '2018-12-21',
			  time: '12:00:00',
			  timezone: '0',
			  dst: 'false'
		      },
		      function(sun_position) {

			  updateSunChart(sun_position);

		      }); {# end getJSON #}

	    return false;

	}); {# end get_darkness_at_noon click #}


	$("#get_no_shadow_at_noon").click(function(e) {

	    $.getJSON($SCRIPT_ROOT + "/api/v1/daily_solar_altitude",
		      {
			  latitude: '23:05',
			  longitude: '32:54',
			  date: '2018-06-21',
			  time: '12:00:00',
			  timezone: '2',
			  dst: 'false'
		      },
		      function(sun_position) {

			  updateSunChart(sun_position);

		      }); {# end getJSON #}

	    return false;

	}); {# end get_no_shadow_at_noon click #}



    }); {# end ready method #}


  </script>

{% endblock %}

{% block title %}Daily Solar Altitude{% endblock %}

{% block content %}

<style>

.page {
    width: 60em;
}

.linechart {
    width: 800px;
    height: 400px;
}

table#sun_chart_legend {
    width: 10em;
}

#_vernal_equinox_txt {
    color: green;
}

#_summer_solstice_txt {
    color: red;
}

#_autumnal_equinox_txt {
    color: orange;
}

#_winter_solstice_txt {
    color: cyan;
}


button#get_daily_solar_altitude {

    text-align: center;

    font-size: 100%;
    font-weight: bold;

    margin: 0 auto;
    display: block;

    width: 100px;
    height: 100px;

    border-radius: 50%;

    color:red;
    background: #ffD700;
}


</style>



<h1>Daily Solar Altitude</h1>

<br>

<div class="twocolumn">

    This shows the
    sun's <a href="https://en.wikipedia.org/wiki/Horizontal_coordinate_system">altitude</a>
    over the current day starting at local midnight. The points where
    the altitude crosses the zero line indicates sun rise and sun set
    (not adjusted for atmospheric refraction). The distance between
    them is the length of the day.  The solstice lines indicate the
    maximum and minimum range of the sun position through out the
    year.

    <p>

    The earth's <a href="https://en.wikipedia.org/wiki/Axial_tilt">axial tilt</a>
    is 23&deg;-ish so a <a href="https://en.wikipedia.org/wiki/Midnight_sun">midnight
      sun</a> happens at an extreme latitude, e.g. near the
    <a href="https://en.wikipedia.org/wiki/Polar_circle">polar
      circle</a>, for example
    <button id="get_midnight_sun">on the summer solstice at 66&deg;N</button>
    Conversly, it is darkness at noon at
    <button id="get_darkness_at_noon">on the winter solstice at 66&deg;N</button>.

    The well that "had no shadow at noon on the solstice"
    <a href="https://en.wikipedia.org/wiki/Eratosthenes#Measurement_of_the_Earth.27s_circumference">
      Eratosthenes uses to calculate the earth's circumference
    </a>
    <button id="get_no_shadow_at_noon">is 23&deg;N and on the summer solstice</button>.


</div>

<br>

{% include "observer_location.html" %}

<br>

<button id="get_daily_solar_altitude">get solar altitude data</button>

<h2>Daily Solar Altitude</h2>


<table>

  <tr>

    <td>
      <div id="altitudeVtime" class="linechart"></div>
    </td>

    <td>

      <table id="sun_chart_legend">

	<tr>

	  <td>
	    <input type="checkbox" id="_vernal_equinox_cb" name="vernal_equinox_cb">
	  </td>

	  <td id="_vernal_equinox_txt">
	    Vernal Equinox
	  </td>

	</tr>

	<tr>

	  <td>
	    <input type="checkbox" id="_summer_solstice_cb" name="summer_solstice_cb" checked>
	  </td>

	  <td id="_summer_solstice_txt">
	    Summer Solstice
	  </td>

	</tr>

	<tr>

	  <td>
	    <input type="checkbox" id="_autumnal_equinox_cb" name="autumnal_equinox_cb">
	  </td>

	  <td id="_autumnal_equinox_txt">
	    Autumnal Equinox
	  </td>

	</tr>

	<tr>

	  <td>
	    <input type="checkbox" id="_winter_solstice_cb" name="winter_solstice_cb" checked>
	  </td>

	  <td id="_winter_solstice_txt">
	    Winter Solstice
	  </td>

	</tr>


      </table>

    </td>

  </tr>

  <tr>
    <td colspan="2">

      <table id="results_table" align="center">

	<tr>
	  <th>Azimuth</th>
	  <td id="azimuth">TBD</td>
	  <td>deg:min:sec (deg)</td>
	</tr>

	<tr>
	  <th>Altitude</th>
	  <td id="altitude">TBD</td>
	  <td>deg:min:sec (deg)</td>
	</tr>

	<tr>
	  <th>Rising</th>
	  <td id="rising">TBD</td>
	  <td>ISO8601</td>
	</tr>


	<tr>
	  <th>Transit</th>
	  <td id="transit">TBD</td>
	  <td>ISO8601</td>
	</tr>

	<tr>
	  <th>Setting</th>
	  <td id="setting">TBD</td>
	  <td>ISO8601</td>
	</tr>

      </table>

    </td>
  </tr>

</table>

{% endblock %}

www/templates/home.html
{% extends "base.html" %}

{% block title %}Astronomical Algorithms Implemented{% endblock %}

{% block content %}


<h1>Astronomical Algorithms Implemented</h1>
<h2>in C++ and</h2>
<h3>Python,</h3>
<h4>JavaScript,</h4>
<h5>html,</h5>
<h6>...</h6>

<br>

<div>

<h2>Contents</h2>

<br>

<table>


  <tr>

    <td>
      <a href="{{ url_for('home_blueprint.lunar_daily_altitude_chart') }}">Solar and Lunar Daily Path</a>
    </td>

    <td>
      Altitude vs Azimuth of the sun and moon at the observer's location over a day.
    </td>

  </tr>


  <tr>

    <td>
      <a href="{{ url_for('home_blueprint.solar_azimuth_map') }}">Solar Azimuth Map</a>
    </td>

    <td>
      Azimuth of the sun at the observer's location.
    </td>

  </tr>


  <tr>

    <td>
      <a href="{{ url_for('home_blueprint.solar_daily_altitude_chart') }}">Solar Daily Altitude</a>
    </td>

    <td>
      Altitude of the sun at the observer's location over a day.
    </td>

  </tr>


  <tr>

    <td>
      <a href="{{ url_for('home_blueprint.transform_observations') }}">Transform Observations</a>
    </td>

    <td>
      Convert between the ecliptic, equatorial and horizontal coordinate systems.
    </td>

  </tr>

  <tr>

    <td>
      <a href="{{ url_for('home_blueprint.transform_times') }}">Transform Times</a>
    </td>

    <td>
      Convert between various time formats.
    </td>

  </tr>

  <tr>
    <td>
      <a href="{{ url_for('home_blueprint.accuracy') }}">On Accuracy</a>
    </td>

  </tr>

</table>

</div>

<hr>

<h2>Introduction</h2>

<br>

<div id="intro" class="twocolumn">

This is my implementation of various astronomical algorithms, mostly
<a href="http://www.willbell.com/math/mc1.htm">Astronomical
Algorithms by Jean Meeus</a>, with parts found around the home and
across the internet.

I use the geolocation capability of a web browser to provide the
observer's location to calculate the azimuth and altitude of the sun
at the current time.

To do this, I pulled together examples of design patterns I have
learned for how to combine C++, Python and JavaScript.

<p>

Access to the implementation here is through a
<a href="http://flask.pocoo.org/">flask server</a> running in a
<a href="https://www.docker.com/">docker container</a>
as a micro-service.

The server provides
an <a href="https://github.com/lrmcfarland/AAI/blob/master/www/api.py">AAI
API</a> to support various operations like transforming an
observer's <a href="https://en.wikipedia.org/wiki/Horizontal_coordinate_system">horizontal
coordinate system</a>
to <a href="https://en.wikipedia.org/wiki/Equatorial_coordinate_system">an
  equatorial</a> one.

This is used to support this web page as well as data operations
for the <a href="https://db.starbug.com/">starbug database</a>
like standardizing input data.

<p>

<a href="http://www.starbug.com">-lrm</a>, <i>2019 Feb 16</i>

</div>

<hr>

<div>

  <h2>Bibliography</h2>

  <table>

    <tr>
      <td>Meeus, Jean</td>
      <td><i>Astronomical Algorithms</i></td>
      <td>Richmond, VA: William-Bell Inc., 2009</td>
    </tr>


    <tr>
      <td>Mills, H. Robert</td>
      <td><i>Practical Astronomy</i></td>
      <td>Chichester, U.K.: Albion Publishing, 1994</td>
    </tr>



    <tr>
      <td>Montenbruck, Oliver and Pfleger, Thomas</td>
      <td><i>Astronomy on the Personal Computer</i></td>
      <td>Heidelberg, Germany: Springer, 2003</td>
    </tr>

  </table>

</div>




{% endblock %}

www/templates/position.html
{# comment #}

{% extends "layout.html" %}
{% block body %}

<h1>Sun Position</h1>

<table id="sunposition">

  <tr>
    <td colspan=3><h2>Observer</h2></td>
  </tr>

  <tr>
    <td>Latitude</td><td> {{ a_latitude }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Longitude</td><td> {{ a_longitude }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Datetime</td><td> {{ a_datetime }} </td><td>ISO8601</td>
  </tr>

  <tr>
    <td colspan=3></td>
  </tr>

  <tr>
    <td colspan=3><h2>Sun</h2></td>
  </tr>

  <tr>
    <td>Distance</td><td> {{ an_r }} </td><td>AU</td>
  </tr>

  <tr>
    <td>Obliquity of the Ecliptic</td><td> {{ an_obliquity }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Ecliptic Longitude</td><td> {{ an_ecl_long }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Solar Declination</td><td> {{ a_dec }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Equation of Time</td><td> {{ an_eot }} </td><td>hours:minutes:seconds</td>
  </tr>

  <tr>
    <td>Rising</td><td> {{ a_rising }} </td><td>ISO8601</td>
  </tr>

  <tr>
    <td>Transit</td><td> {{ a_transit }} </td><td>ISO8601</td>
  </tr>

  <tr>
    <td>Setting</td><td> {{ a_setting }} </td><td>ISO8601</td>
  </tr>

  <tr>
    <td>Azimuth</td><td> {{ an_azimuth }} </td><td>degrees:minutes:seconds</td>
  </tr>

  <tr>
    <td>Altitude</td><td> {{ an_altitude }} </td><td>degrees:minutes:seconds</td>
  </tr>

</table>

{% endblock %}

www/templates/sun_position_form.html
{# comment #}

{% extends "base.html" %}
{% block content %}

<div>
  <table id="observerlocation">

    <tr>
      <td colspan=3><h2>Observer Location</h2></td>
    </tr>

    <tr>
      <td>Latitude</td><td> {{ latitude }} </td><td>deg:min:sec</td>
    </tr>

    <tr>
      <td>Longitude</td><td> {{ longitude }} </td><td>deg:min:sec</td>
    </tr>

    <tr>
      <td>Datetime</td><td> {{ datetime }} </td><td>ISO8601</td>
    </tr>

  </table>

</div>

<hr>

<div>
  <table id="sunposition">

    <tr>
      <td colspan=3></td>
    </tr>

    <tr>
      <td colspan=3><h2>Sun Position</h2></td>
    </tr>

    <tr>
      <td>Distance</td><td> {{ R }} </td><td>AU</td>
    </tr>

    <tr>
      <td>Obliquity</td><td> {{ obliquity }} </td><td>deg:min:sec</td>
    </tr>

    <tr>
      <td>Solar Declination</td><td> {{ dec }} </td><td>deg:min:sec</td>
    </tr>

    <tr>
      <td>Ecliptic Longitude</td><td> {{ ecliptic_longitude }} </td><td>deg:min:sec</td>
    </tr>

    <tr>
      <td>Equation of Time</td><td> {{ eot }} </td><td>hours:min:sec</td>
    </tr>

    <tr>
      <td>Azimuth</td><td> {{ azimuth }} </td><td>deg:min:sec (deg)</td>
    </tr>

    <tr>
      <td>Altitude</td><td> {{ altitude }} </td><td>deg:min:sec (deg)</td>
    </tr>

    <tr>
      <td>Rising</td><td> {{ rising }} </td><td>ISO8601</td>
    </tr>

    <tr>
      <td>Transit</td><td> {{ transit }} </td><td>ISO8601</td>
    </tr>

    <tr>
      <td>Setting</td><td> {{ setting }} </td><td>ISO8601</td>
    </tr>


  </table>
</div>

{% endblock %}

www/templates/transforms.html
{# flask ajax example #}

{% extends "base.html" %}

{% block scripts %}

<style>


table#coordinates_table {
    width: 80%;
    margin-left: 10%;
    margin-right: 10%;

}

</style>

<script type="text/javascript">

  $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};



  $(function() {

      $("#_dms").change(function() {

	  $.getJSON($SCRIPT_ROOT + "/api/v1/dms2dec", {
	      dms: $('input[name="dms"]').val(),
	  },

	  function(data) {

	      if ("error" in data) {

		  alert("Error: " + data.error);

		  $("#_dec").val("TBD");

	      } else {

		  $("#_dec").val(data.dec);

	      };

	  });

      }); {# end _dms.change #}


      $("#_dec").change(function() {

	  $.getJSON($SCRIPT_ROOT + "/api/v1/dec2dms", {
	      dec: $('input[name="dec"]').val(),
	  },

	  function(data) {

	      if ("error" in data) {

		  alert("Error: " + data.error);

		  $("#_dms").val("TBD");

	      } else {

		  $("#_dms").val(data.dms);

	      };

	  });

      }); {# end _dec.change #}



  }); {# end jquery init function #}





</script>

{% endblock %}

{% block title %} Deg:Min:Sec to Decimal degree Transforms {% endblock %}

{% block content %}

<h1>Transforms</h1>

<br>

<div>


  <h2>Deg:Min:Sec (DMS) to Decimal transforms</h2>
  <p>
    This page transforms coordinates between
    degree/hour:minute:second notation to the decimal equivalent.
  </p>

</div>

<br>

<div class="resultbox">

  <table id="coordinates_table">

    <tr>

      <th align="center">Deg:Min:Sec</th>
      <td></td>
      <th align="center">Decimal Degrees</th>

    </tr>

    <tr>

      <td align="center"><input type="text" name="dms" id="_dms" value="0"></td>
      <td></td>
      <td align="center"><input type="text" name="dec" id="_dec" value="0"></td>

    </tr>


  </table>

</div>


{% endblock %}